const flatbuffers = require('./libs/flatbuffers/flatbuffers').flatbuffers;
const ProductOffering = require('./data/po_generated').ProductOffering; // Generated by `flatc`.

const builder = new flatbuffers.Builder(0);
const name = builder.createString('Облачный');
const version = builder.createString('1.1');
ProductOffering.Offer.startOffer(builder)
ProductOffering.Offer.addName(builder, name);
ProductOffering.Offer.addVersion(builder, version);
ProductOffering.Offer.addStatus(builder, ProductOffering.LifecycleStatus.Project)
const offer = ProductOffering.Offer.endOffer(builder);
builder.finish(offer);

// сетевая передача в бинарном формате
const buf = builder.dataBuffer();
const transportOffer = ProductOffering.Offer.getRootAsOffer(buf);
console.log(transportOffer.name())
console.log(transportOffer.version())
console.log(transportOffer.status())
